"use client";

import { useEffect, useState } from "react";
import AdminLayout from "../../../components/layout/AdminLayout";
import { api } from "../../../lib/api";

const emptyZone = { name: "", countryCode: "IN", stateName: "", fulfillmentMode: "FLAT", flatRateRupees: "", isEnabled: true, priority: "100" };
const emptyPolicy = { freeShippingEnabled: false, freeShippingThresholdRupees: "", internationalFallbackMode: "CONTACT_US" };
const money = (paise) => paise === null || paise === undefined ? "Contact us" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(Number(paise) / 100);
const zoneForm = (zone) => zone ? { ...zone, flatRateRupees: zone.flatRatePaise === null ? "" : String(Number(zone.flatRatePaise) / 100) } : emptyZone;
const policyForm = (policy) => ({ ...emptyPolicy, ...policy, freeShippingThresholdRupees: policy?.freeShippingThresholdPaise === null || !policy ? "" : String(Number(policy.freeShippingThresholdPaise) / 100) });

function ZoneForm({ zone, onSave, saving, cancel }) {
  const [form, setForm] = useState(zoneForm(zone));
  const change = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event) => {
    event.preventDefault();
    onSave({ ...form, stateName: form.stateName || null, flatRatePaise: form.fulfillmentMode === "FLAT" ? Math.round(Number(form.flatRateRupees) * 100) : null, priority: Number(form.priority) });
  };
  return <form onSubmit={submit} className="mt-4 grid gap-3 rounded-xl border border-stone-700 bg-[#120f1d] p-4 sm:grid-cols-2">
    <label className="text-sm">Zone name<input required value={form.name} onChange={(e) => change("name", e.target.value)} className="mt-1 w-full rounded border border-stone-700 bg-[#0c0816] p-2 text-white" /></label>
    <label className="text-sm">Country<select value={form.countryCode} onChange={(e) => change("countryCode", e.target.value)} className="mt-1 w-full rounded border border-stone-700 bg-[#0c0816] p-2 text-white"><option value="IN">India</option><option value="*">International</option></select></label>
    <label className="text-sm">State match (optional)<input value={form.stateName || ""} onChange={(e) => change("stateName", e.target.value)} placeholder="Tamil Nadu" className="mt-1 w-full rounded border border-stone-700 bg-[#0c0816] p-2 text-white" /></label>
    <label className="text-sm">Priority (lower wins)<input required min="0" type="number" value={form.priority} onChange={(e) => change("priority", e.target.value)} className="mt-1 w-full rounded border border-stone-700 bg-[#0c0816] p-2 text-white" /></label>
    <label className="text-sm">Delivery result<select value={form.fulfillmentMode} onChange={(e) => change("fulfillmentMode", e.target.value)} className="mt-1 w-full rounded border border-stone-700 bg-[#0c0816] p-2 text-white"><option value="FLAT">Flat rate</option><option value="CONTACT_US">Contact us</option></select></label>
    {form.fulfillmentMode === "FLAT" ? <label className="text-sm">Shipping rate (₹)<input required min="0" step="0.01" type="number" value={form.flatRateRupees ?? ""} onChange={(e) => change("flatRateRupees", e.target.value)} className="mt-1 w-full rounded border border-stone-700 bg-[#0c0816] p-2 text-white" /><span className="mt-1 block text-xs text-stone-500">Customers see this rate only after their delivery address is checked.</span></label> : <p className="self-end text-sm text-stone-400">Customers will be asked to contact support for this destination.</p>}
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(form.isEnabled)} onChange={(e) => change("isEnabled", e.target.checked)} /> Enable this zone</label>
    <div className="flex gap-3"><button disabled={saving} className="rounded bg-[#d4af37] px-4 py-2 text-sm font-bold text-[#0c0816] disabled:opacity-60">{saving ? "Saving…" : "Save zone"}</button>{cancel ? <button type="button" onClick={cancel} className="rounded border border-stone-600 px-4 py-2 text-sm">Cancel</button> : null}</div>
  </form>;
}

function ShippingSettings() {
  const [zones, setZones] = useState([]); const [policy, setPolicy] = useState(emptyPolicy); const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [editing, setEditing] = useState(null); const [adding, setAdding] = useState(false); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); setError(""); try { const data = (await api.shipping.admin.getSettings())?.data || {}; setZones(data.zones || []); setPolicy(policyForm(data.policy)); } catch (e) { setError(e?.message || "Shipping settings could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const savePolicy = async (event) => { event.preventDefault(); setSaving(true); setError(""); setMessage(""); try { const response = await api.shipping.admin.updateSettings({ freeShippingEnabled: policy.freeShippingEnabled, freeShippingThresholdPaise: policy.freeShippingEnabled ? Math.round(Number(policy.freeShippingThresholdRupees) * 100) : null, internationalFallbackMode: "CONTACT_US" }); setPolicy(policyForm(response.data)); setMessage("Free-shipping policy saved."); } catch (e) { setError(e?.message || "Policy could not be saved."); } finally { setSaving(false); } };
  const saveZone = async (zone) => { setSaving(true); setError(""); setMessage(""); try { const response = editing ? await api.shipping.admin.updateZone(editing.id, zone) : await api.shipping.admin.createZone(zone); const saved = response.data; setZones((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [...current, saved].sort((a, b) => a.priority - b.priority)); setEditing(null); setAdding(false); setMessage("Shipping zone saved."); } catch (e) { setError(e?.message || "Zone could not be saved."); } finally { setSaving(false); } };
  if (loading) return <AdminLayout><p className="p-8 text-stone-300">Loading shipping settings…</p></AdminLayout>;
  return <AdminLayout><main className="mx-auto max-w-4xl space-y-8 p-5 text-stone-200 sm:p-8"><header><p className="text-xs font-semibold uppercase tracking-[0.28em] text-[#d4af37]">Store settings</p><h1 className="mt-2 font-serif text-3xl text-white">Shipping</h1><p className="mt-2 text-sm text-stone-400">Rates are specific to this store. A lower priority wins; exact state matches win before the general India zone.</p></header>{error ? <p role="alert" className="rounded border border-rose-900 bg-rose-950/30 p-3 text-sm text-rose-200">{error}</p> : null}{message ? <p role="status" className="rounded border border-emerald-900 bg-emerald-950/30 p-3 text-sm text-emerald-200">{message}</p> : null}
    <section className="rounded-2xl border border-stone-800 bg-[#161022] p-5"><h2 className="font-serif text-xl text-white">Free shipping</h2><form onSubmit={savePolicy} className="mt-4 grid gap-4 sm:grid-cols-2"><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={Boolean(policy.freeShippingEnabled)} onChange={(e) => setPolicy((p) => ({ ...p, freeShippingEnabled: e.target.checked }))} /> Enable free shipping by jewellery subtotal</label>{policy.freeShippingEnabled ? <label className="text-sm">Jewellery subtotal threshold (₹)<input required min="0" step="0.01" type="number" value={policy.freeShippingThresholdRupees ?? ""} onChange={(e) => setPolicy((p) => ({ ...p, freeShippingThresholdRupees: e.target.value }))} className="mt-1 w-full rounded border border-stone-700 bg-[#0c0816] p-2 text-white" /><span className="mt-1 block text-xs text-stone-500">GST stays separate and shipping is not included in its calculation.</span></label> : null}<p className="self-end text-sm text-stone-400">International and unmatched destinations always use <strong>Contact us</strong>.</p><button disabled={saving} className="w-fit rounded bg-[#d4af37] px-4 py-2 text-sm font-bold text-[#0c0816] disabled:opacity-60">Save policy</button></form></section>
    <section className="rounded-2xl border border-stone-800 bg-[#161022] p-5"><div className="flex items-center justify-between gap-4"><div><h2 className="font-serif text-xl text-white">Shipping zones</h2><p className="mt-1 text-sm text-stone-400">Disabled zones are never selected at checkout.</p></div><button onClick={() => { setAdding(true); setEditing(null); }} className="rounded border border-[#d4af37] px-4 py-2 text-sm text-[#e5c865]">Add zone</button></div>{adding ? <ZoneForm onSave={saveZone} saving={saving} cancel={() => setAdding(false)} /> : null}<div className="mt-4 space-y-3">{zones.length ? zones.map((zone) => <div key={zone.id} className="rounded-xl border border-stone-800 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-white">{zone.name} {!zone.isEnabled ? <span className="ml-2 text-xs font-normal text-amber-300">Disabled</span> : null}</p><p className="mt-1 text-sm text-stone-400">{zone.countryCode === "IN" ? "India" : "International"}{zone.stateName ? ` · ${zone.stateName}` : ""} · Priority {zone.priority}</p><p className="mt-1 text-sm text-stone-300">{zone.fulfillmentMode === "FLAT" ? money(zone.flatRatePaise) : "Contact us"}</p></div><button onClick={() => { setEditing(zone); setAdding(false); }} className="rounded border border-stone-600 px-3 py-2 text-sm">Edit</button></div>{editing?.id === zone.id ? <ZoneForm zone={editing} onSave={saveZone} saving={saving} cancel={() => setEditing(null)} /> : null}</div>) : <p className="text-sm text-stone-400">No shipping zones are configured yet.</p>}</div></section></main></AdminLayout>;
}
export default function ShippingPage() { return <ShippingSettings />; }
