"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useCustomerAuth } from "../../../components/hooks/useCustomerAuth";
import OrderPurchaseActions from "../../../components/orders/OrderPurchaseActions";
import { api } from "../../../lib/api";

const initialPagination = { page: 1, limit: 20, total: 0, hasNext: false, hasPrevious: false };
const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
const date = (value) => (value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium" }).format(new Date(value)) : "—");

export default function MyOrders() {
  const router = useRouter();
  const { customer, isLoading: authLoading } = useCustomerAuth(); const [orders, setOrders] = useState([]); const [pagination, setPagination] = useState(initialPagination); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { if (!authLoading && !customer) router.replace("/"); }, [authLoading, customer, router]);
  useEffect(() => { if (!customer) return undefined; let active = true; async function load() { setLoading(true); try { const response = await api.orders.mine({ page: pagination.page, limit: pagination.limit }); if (!active) return; setOrders(response?.data?.orders || []); setPagination((current) => ({ ...current, ...(response?.data?.pagination || initialPagination) })); setError(""); } catch (requestError) { if (active) setError(requestError?.message || "Unable to load orders."); } finally { if (active) setLoading(false); } } void load(); return () => { active = false; }; }, [customer, pagination.page, pagination.limit]);
  if (authLoading || !customer) return <main className="min-h-screen bg-[#0f0a1a]" />;
  return <main className="min-h-screen bg-[#0f0a1a] px-4 py-20 text-stone-200 sm:px-6"><section className="mx-auto max-w-4xl"><div className="flex items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.28em] text-[#d4af37]">Your collection</p><h1 className="mt-2 font-serif text-3xl text-white">My orders</h1></div><Link href="/account" className="text-sm text-[#d4af37]">My Account</Link></div>{loading ? <p className="mt-8 text-stone-400" role="status">Loading orders…</p> : null}{error ? <p className="mt-8 text-rose-300" role="alert">{error}</p> : null}<div className="mt-7 space-y-4">{orders.map((order) => { const previews = order.itemPreviews || []; const first = previews[0]; return <article key={order.orderNumber} className="rounded-xl border border-stone-800 bg-[#161022] p-5"><div className="flex flex-col gap-5 sm:flex-row"><div className="flex shrink-0 -space-x-3">{previews.map((item) => <div key={item.productId} className="h-16 w-16 overflow-hidden rounded border-2 border-[#161022] bg-[#0f0a1a]">{item.imageUrl ? <img src={item.imageUrl} alt="" className="h-full w-full object-cover" /> : null}</div>)}</div><div className="min-w-0 flex-1"><Link href={`/account/orders/${encodeURIComponent(order.orderNumber)}`} className="font-serif text-xl text-white hover:text-[#d4af37]">{order.orderNumber}</Link><p className="mt-1 text-sm text-stone-400">{date(order.createdAt)} · {first?.productName || "Order items"}{order.itemCount > 1 ? ` +${order.itemCount - 1} more` : ""}</p><p className="mt-3 text-sm text-stone-300">{money(order.totalAmount)} · Payment {order.paymentStatus} · {order.status}</p></div><div className="flex flex-wrap content-start gap-2"><Link href={`/account/orders/${encodeURIComponent(order.orderNumber)}`} className="rounded border border-stone-700 px-3 py-2 text-xs text-stone-200">View Order</Link>{first ? <OrderPurchaseActions item={first} compact /> : null}</div></div></article>; })}</div>{!loading && !error && orders.length === 0 ? <p className="mt-8 text-stone-400">No orders yet. <Link href="/products" className="text-[#d4af37]">Explore the collection</Link>.</p> : null}<div className="mt-8 flex items-center justify-between text-sm text-stone-400"><span>{pagination.total} order{pagination.total === 1 ? "" : "s"}</span><div className="flex gap-2"><button type="button" disabled={!pagination.hasPrevious} onClick={() => setPagination((current) => ({ ...current, page: current.page - 1 }))} className="rounded border border-stone-700 px-3 py-2 disabled:opacity-40">Previous</button><button type="button" disabled={!pagination.hasNext} onClick={() => setPagination((current) => ({ ...current, page: current.page + 1 }))} className="rounded border border-stone-700 px-3 py-2 disabled:opacity-40">Next</button></div></div></section></main>;
}
