"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { formatAdminDateTime } from "../../lib/adminDate";
import { publishNotificationCount } from "../../lib/notificationCount";

export default function NotificationList({ load, markRead, markAllRead, admin = false }) {
  const [data, setData] = useState(null); const [page, setPage] = useState(1); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const audience = admin ? "admin" : "customer";
  const refresh = useCallback(async () => { try { setError(""); const response = await load({ page, limit: 20 }); setData(response.data); publishNotificationCount(audience, response.data?.unreadCount || 0); } catch (cause) { setError(cause.message || "Unable to load notifications."); } }, [audience, load, page]);
  useEffect(() => { void refresh(); }, [refresh]);
  const read = async (notification) => { if (notification.readAt) return; try { await markRead(notification.id); await refresh(); } catch (cause) { setError(cause.message || "Unable to update notification."); } };
  const readEverything = async () => { setBusy(true); try { await markAllRead(); publishNotificationCount(audience, 0); await refresh(); } catch (cause) { setError(cause.message || "Unable to update notifications."); } finally { setBusy(false); } };
  const pagination = data?.pagination;
  return <section className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.28em] text-[#d4af37]">{admin ? "Operations" : "Your account"}</p><h1 className="mt-2 font-serif text-3xl text-white">Notifications</h1><p className="mt-2 text-sm text-stone-400">{data ? `${data.unreadCount} unread` : "Loading updates…"}</p></div><button type="button" disabled={busy || !data?.unreadCount} onClick={readEverything} className="rounded border border-stone-700 px-4 py-2 text-sm text-stone-200 disabled:opacity-40">Mark all read</button></div>{error ? <p role="alert" className="text-rose-300">{error}</p> : null}<div className="overflow-hidden rounded-xl border border-stone-800 bg-[#161022]">{!data ? <p className="p-6 text-stone-400">Loading notifications…</p> : null}{data?.notifications?.length === 0 ? <p className="p-8 text-stone-400">You’re all caught up.</p> : null}{data?.notifications?.map((notification) => <article key={notification.id} className={`border-b border-stone-800 p-5 last:border-0 ${notification.readAt ? "" : "bg-[#21192f]"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#d4af37]">{notification.eventType.replaceAll("_", " ")}</p><h2 className="mt-1 font-semibold text-white">{notification.title}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-stone-300">{notification.message}</p><p className="mt-2 text-xs text-stone-500">{formatAdminDateTime(notification.createdAt)}</p></div>{!notification.readAt ? <button type="button" onClick={() => read(notification)} className="text-xs text-[#d4af37]">Mark read</button> : null}</div><div className="mt-4 flex flex-wrap gap-4 text-sm">{admin ? <Link href={`/admin/notifications/${encodeURIComponent(notification.id)}`} onClick={() => read(notification)} className="text-[#d4af37] hover:text-[#edca65]">View delivery details →</Link> : null}{notification.actionUrl ? <Link href={notification.actionUrl} onClick={() => read(notification)} className="text-stone-300 hover:text-white">Open related record →</Link> : null}</div></article>)}</div>{data ? <div className="flex items-center justify-between text-sm text-stone-400"><span>{pagination.total} notification{pagination.total === 1 ? "" : "s"}</span><div className="flex gap-2"><button type="button" disabled={!pagination.hasPrevious} onClick={() => setPage((value) => value - 1)} className="rounded border border-stone-700 px-3 py-2 disabled:opacity-40">Previous</button><button type="button" disabled={!pagination.hasNext} onClick={() => setPage((value) => value + 1)} className="rounded border border-stone-700 px-3 py-2 disabled:opacity-40">Next</button></div></div> : null}</section>;
}
